### ISSUE TITLE
[Feature Request] Sort programs based on frequency of opening/using it.

### ISSUE THREAD

**Issue by Dev123456689** [Flow-Launcher/Flow.Launcher.Plugin.Program#1]
It will be very nice if the plugin can **sort programs based on how frequently i use them**, as current many unwanted programs / windows tools comes to the top instead of the programs i want to use.

**For example**: i am searching for a program named 'Revo Uninstaller', when i type '_re_' it pops up with Registry editor, recovery drive, report a problem to unity, realtek audio console, resource monitor, remote desktop connection, revo uninstaller Website (many programs put such things in the start menu) and what not at the top, and **i have to type the full name of the programs or to scroll down to open the programs both of which i dislike**.
I know that i can pin programs at the top but how many programs will i go and pin, and it gets pin at the top for that string only, what if i trype 'rev' instead of 're', everything is back to where i started. I am very frustrated about it.

**Sorting a program with how often i open it feels like avery good solution to me. Additionally, you can sort user installed programs at the top for users using it for the first time of whom their is no data to use and figure out a filter what would lower the ranking of webpages, manuals, help page and uninstaller of the programs, that many programs like to put in the start menu. Due to the lack of such features searcing for programs in the start menu feels a lot better than using flow launcher.** 

**Finally, button for reaching the homepage of the plugin should land us in this ([Flow.Launcher.Plugin.Program](https://github.com/Flow-Launcher/Flow.Launcher.Plugin.Program)) Github repository instead of [Flow.Launcher](https://github.com/Flow-Launcher/Flow.Launcher) repository.**

I hope you will consider to add such features in the Programs plugin for its improvement, thanks for listening to all my requests and complaints, waiting for your view on this matter.

**Comment by Dev123456689** [comment]
i don't know how it does sorting but sometimes it feels like it is sorting based on which program i open on typing a particular string and shows that program at the top next time i type exactly same string. I hope you are woking on improving it.

**Comment by jjw24** [comment]
This is already implemented, you will need to select a couple of times in order for it to be effective especially if only 2 character searches it could return numerous results. You can further prioritise certain plugin results via the plugin settings so results from program plugin will be on top of other plugin results.

**Comment by jjw24** [comment]
> Finally, button for reaching the homepage of the plugin should land us in this (Flow.Launcher.Plugin.Program) Github repository instead of Flow.Launcher repository.

The plugin link in your comment actually is the repo just for holding plugin releases. Program plugin and all plugins publisher with flow itself should already be landing the homepage at e.g. https://github.com/Flow-Launcher/Flow.Launcher/tree/dev/Plugins/Flow.Launcher.Plugin.Program, so people can inspect the code. Let me know if not the case, thought I made this change already.

**Comment by Dev123456689** [comment]
> This is already implemented, you will need to select a couple of times in order for it to be effective 

Thanks, i think i filed an issue without having proper knowledge.

**Comment by Dev123456689** [comment]
> This is already implemented, you will need to select a couple of times in order for it to be effective

Thanks, i think i filed an issue without having proper knowledge.
